#+TITLE: a systematic killing of curiosity 
#+DATE: [2026-05-07 Tue 09:09]

the indian education system is the best example of a legal cage where *millions of students* are stuck and hundereds and thousands of students give their life up.
it all starts in grade 10th we start to understand what eneternce exams are or its even earlier for some kids whose parents are a little too much paranoid, =JEE= and =NEET= are the main ones in this game. but lets call it what it actually is =a systematic curiosity killer=. we dont produce engineers and doctors, we either produce *trauma survivors* and *dead kids*. seeing a couple *suicide letter* on reddit a day during the exam season from feb to june is the new normal now. this happens way too often than anything of this magnitude should be accepted.

* the start
now that we have gotten the preface of this journey, lets start at the beginning of the journey (/atleast for most of the aspirants/). it starts as your relatives or your neighbours realize you are in 10th grade and are ready to get into =entrance exam game= start telling you and your parents about the undergrad college exams to get government colleges and stuff. it seems fun at first, everyone encouraging you to do it saying that you can do it you are very smart (atleast most of the times). you and your parents go to the coaching institutes you have heard from friends who have already joined in 10th or are planning to. you start seeing those allen ads where they say "/your kids gonna fall behind if he does not join allen/", then after you have shortlisted all the coaching centers you find good and go to each one of them, they manipulate you into thinking that you need =JEE= or =NEET= to do something in life, if you dont do this you are going to fail do nothing, =you are going to be a failure=. you give the institute entrance exam to get scholarship, the percentage or percentile you get is the amount of scholarship give, fun idea, bad execution it becomes a decider if you are worth it or not, decides if you go there or no, decides if you ever meet your school friends or not. not everyone has the privilege to have /good/ coaching in their home town or village, so they have to go out of their home to another city study, away from family, friends and their world, all this happens for 2 years or 3 if you take a drop.

* the journey
now you have choosen the coaching institute and the 2 year grind starts. you also join a dummy or a tie-up college where you only give exams that come to you or are mostly optional. it all seems fun and games at first, you understand stuff, start studying a little bit, you get new friends. thats what happens for the first year till grade 11. you try to get good marks in monthly and weekly mock tests (it your institute takes it this early). then grade 11th ends, you see the passouts donig good or bad asking them for advice, some tell you its gonna be fine, others have just lost it. but you still go through and try managing =JEE/NEET= studies with college boards studies for 12th which becomes hectic, you start loosing friends, you go coaching and then directly come home, loose social interaction other than coaching, life starts becoming hell or it slowly does. you start cramming as much information as possible rote learn chemistry reactions, reagents, catalyst, properties but it gets beyond control, you try learning physics formule, you are good at physics, but having 1000 formulae's does not help your case. whereas maths and biology are their own beasts who require you to understand the ins and outs of it to really start scoring in them.

* the doomsday
now that you have done 2 years of coaching here comes the exam season. you first start with =JEE= in feb and funnily enough it clashes with your boards exam or atleast your boards practicals every single time! and then you realize it wasnt good enough, you focus on attempt 2 of =JEE=, and then boards are over, you knew the concepts but you could not tell them in the paper, you could not derive formule or methods because you only knew the shortcut your institute gave and they just say boards are peanuts who cares about those anyways.
now comes the twister, you get your options on the sidelines such as =MHT CET= right before your =JEE attempt 2=, you are like what, even tho the syllabus is mostly the same, the technique for solving =MHT CET= is totally different, its a whole another approach you have to take for this kind of fast paced exam. you try solving =MHT CET= mock test you dont really know how to manage time, you are now stuck in a dilema to do =JEE attempt 2= or =MHT CET=, choosing the wrong one could be fatal. you try to cram the preperation for both exams, it is chaotic but you somehow manage it. a lot of people have give everything up, but you are still going like the other more than a =million students= also stuck in this

* the aftermath
everything now is done after all the exams, you feel weird to have to do nothing for around the first time in 2 years, have soo much free time to waste, you go out, watch movies, watch the shows you have been keeping forward for a long time, you rewatch some content you love, play some games, go back to you hobbies, doing your hobbies, you are in this limbo where =you are not studying= nor are you =resting=. but this does not last long just in like a week or two comes the results for =JEE/NEET= and/or =your state exam=, if you had studied well you might have gotten good marks, but like the other million or two million students, you are stuck in a dilema, you did alright but not good enough to go anywhere, you dont know what do you want to do in life, you cannot differentiate or integrate the hobbies you do, you cannot calculate the probablity of you being sucessful just according to the marks you get, you are stuck!
you spent 2 years doing rote learning =organic equations=, =calculus= and =viscosity of honey= for it to be irrelevent in a matter of days, this is all useless information for you now, you will most probally not need any of this information for the rest of your life. you try finding this in your real life weirdly to see if these things apply but it makes you not appreciate the nature and the place you live in.

now the results drop in, you put in your seat number and password. it crashes the first time you retry. it opens this time, you check into it, and wow who would have guessed you are not a topper, you probably got a ~70-80% or percentile in your exams, that is the only reason you hate this system and are reading this post. like the million other lost souls you are wondering, what did you do wrong. or maybe you know what went wrong and now you regret it. you cannot do anything now other than waste another year of life to take a drop and redo the enterence exams again, i would /kms/ if i had to do that. but a lot of do take a drop just to try to improve for next year to again fail at it, wasting another year of their life at a useless exam.

* the tragedy
you have a truckload of knowledge but you have lost the ability to appreciate the sweetness in understanding it. your story might be nominal when compared to the students who try to end it all, its not uncommon to find atleast *~2-3 suicide notes* on reddit every single day in the exam season. a lot of them are with a lot of detail about the mental and physical trauma they have gone through these 2 years. /a lot are saved but not everyone/.
you might have gotten a decent college, or even a good one, but you realize the system isnt build for you to understand or learn anything it just wants the sweetness paychecks you bring, this has become a industry. you entered this as a child with =dreams and personality= but you left with big war scar or died along the way. you have atleast survived through this, ... but *did you actually win?*
